# Generated by Django 5.1.7 on 2025-05-14 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='DIYVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video', models.FileField(upload_to='diy_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='diy_thumbnails/')),
                ('creater_at', models.DateTimeField(auto_now_add=True)),
                ('tools_used', models.ManyToManyField(blank=True, to='shop.product')),
            ],
        ),
    ]
