# Generated by Django 5.1.7 on 2025-05-14 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_diyvideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diyvideo',
            old_name='creater_at',
            new_name='created_at',
        ),
    ]
