# Generated by Django 5.1.7 on 2025-05-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_creater_at_diyvideo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='diyvideo',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='diy_video_thumbnails/'),
        ),
    ]
