# Generated by Django 5.1.7 on 2025-05-31 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_phone_order_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
