# Generated by Django 5.1.7 on 2025-06-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_category_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
