# Generated by Django 5.1.7 on 2025-06-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
    ]
